name: spresense-arduino

on: [push, pull_request]

jobs:
  build:
    name: Build sample project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli config init --additional-urls https://github.com/sonydevworld/spresense-arduino-compatible/releases/download/generic/package_spresense_index.json
          arduino-cli core update-index
          arduino-cli core search spresense
          arduino-cli core install SPRESENSE:spresense
          arduino-cli lib install ArduinoJson@5.13.5
      - name: Compile Sketch
        run: arduino-cli compile --fqbn SPRESENSE:spresense:spresense ./src/main
